/*
  # Fix purchase order ID columns to allow explicit values

  1. Problem
    - The purchase_orders and purchase_order_lines tables use IDENTITY columns
    - These are set to GENERATED ALWAYS, which prevents inserting explicit values
    - The Rackbeat API provides IDs that we want to preserve

  2. Solution
    - Drop and recreate the identity property with GENERATED BY DEFAULT
    - This allows explicit values while still generating IDs when needed
    - Preserve existing data and constraints
*/

-- For purchase_orders table
ALTER TABLE purchase_orders 
ALTER COLUMN id DROP IDENTITY IF EXISTS;

ALTER TABLE purchase_orders 
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- For purchase_order_lines table
ALTER TABLE purchase_order_lines 
ALTER COLUMN id DROP IDENTITY IF EXISTS;

ALTER TABLE purchase_order_lines 
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Log the change
INSERT INTO function_logs (function_name, log_message)
VALUES (
  'migration',
  'Changed ID columns in purchase_orders and purchase_order_lines tables from GENERATED ALWAYS to GENERATED BY DEFAULT to allow explicit ID values from Rackbeat API'
);