/*
  # Fix purchase order ID columns to allow explicit values

  1. Problem
    - The purchase_orders and purchase_order_lines tables use IDENTITY columns
    - These are currently set as GENERATED ALWAYS, which prevents explicit ID values
    - The Rackbeat API provides IDs that we want to preserve

  2. Solution
    - Drop and recreate the identity property with GENERATED BY DEFAULT
    - This allows explicit ID values while still generating them when needed
    - Preserve existing data during the change
*/

-- For purchase_orders table
-- First, drop the identity property
ALTER TABLE purchase_orders 
ALTER COLUMN id DROP IDENTITY IF EXISTS;

-- Then recreate it with GENERATED BY DEFAULT
ALTER TABLE purchase_orders 
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- For purchase_order_lines table
-- First, drop the identity property
ALTER TABLE purchase_order_lines 
ALTER COLUMN id DROP IDENTITY IF EXISTS;

-- Then recreate it with GENERATED BY DEFAULT
ALTER TABLE purchase_order_lines 
ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Log the change
INSERT INTO function_logs (function_name, log_message)
VALUES (
  'migration',
  'Changed ID columns in purchase_orders and purchase_order_lines tables from GENERATED ALWAYS to GENERATED BY DEFAULT to allow explicit ID values from Rackbeat API'
);